### ISSUE TITLE
Non IC crashes due to typo

### ISSUE THREAD

**Issue by MrMondrian** [DDMAL/Rodan#1029]
My local E2E crashed in nic from what appears to be a typo
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 773, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/gamera_rodan/wrappers/classification.py", line 93, in run_my_task
    cknn.load_settings(inputs['GameraXML - Feature Selection'][0]['resource_path'])
  File "/usr/local/lib/python3.7/site-packages/gamera/knn.py", line 319, in load_settings
    self.num_k = loader.num_k
TypeError: knn: expected an int.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 429, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 366, in on_error
    task, request, eager=eager, call_errbacks=call_errbacks,
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 173, in handle_error_state
    call_errbacks=call_errbacks)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 221, in handle_failure
    task.on_failure(exc, req.id, req.args, req.kwargs, einfo)
  File "/code/Rodan/rodan/jobs/base.py", line 1015, in on_failure
    and user.user_preference.sned_email
AttributeError: 'UserPreference' object has no attribute 'sned_email'
```

**Comment by MrMondrian** [comment]
The bug was introduced in [this commit](https://github.com/DDMAL/Rodan/commit/67c35db650966646550a477e8a708c68ff13e035) 3 years ago

**Comment by MrMondrian** [comment]
I believe the first error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 773, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/gamera_rodan/wrappers/classification.py", line 93, in run_my_task
    cknn.load_settings(inputs['GameraXML - Feature Selection'][0]['resource_path'])
  File "/usr/local/lib/python3.7/site-packages/gamera/knn.py", line 319, in load_settings
    self.num_k = loader.num_k
TypeError: knn: expected an int.
```
was caused by passing the training data resource into the feature selection port of nic. This triggered a failure case in rodan that has a typo which threw another error
