### ISSUE TITLE
Help needed: specific folios failing consistently

### ISSUE THREAD

**Issue by JoyfulGen** [DDMAL/Rodan#1124]
There are a few folios in Einsie that provoke a job failure every time I try to run them through an e2e OMR workflow. And I don't know why! I'll make a separate comment for each folio to keep it organized.

**Comment by JoyfulGen** [comment]
**Folio 269v** - MEI encoding job fails
Error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 773, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/MEI_encoding/MEI_encoding.py", line 98, in run_my_task
    mei_string = bm.process(jsomr, syls, classifier_table, width_mult, width_container, split_ranges)
  File "/code/Rodan/rodan/jobs/MEI_encoding/build_mei_file.py", line 855, in process
    pairs, classifier, width_container, staves, jsomr["page"], column_split_info
  File "/code/Rodan/rodan/jobs/MEI_encoding/build_mei_file.py", line 606, in build_mei
    bb = system_boxes[0]
IndexError: list index out of range
```

Image: 
[Einsiedeln__Stiftsbibliothek__Codex_611_269v.jpg.zip](https://github.com/DDMAL/Rodan/files/14010286/Einsiedeln__Stiftsbibliothek__Codex_611_269v.jpg.zip)
Text file:
[269v.txt](https://github.com/DDMAL/Rodan/files/14010279/269v.txt)

**Comment by JoyfulGen** [comment]
**Folio 186r** - Miyao staff finding job fails

Error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 773, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/heuristic_pitch_finding/base.py", line 77, in run_my_task
    staves = sf.get_staves(image)
  File "/code/Rodan/rodan/jobs/heuristic_pitch_finding/StaffFinding.py", line 33, in get_staves
    self._find_staves(s)
  File "/code/Rodan/rodan/jobs/heuristic_pitch_finding/StaffFinding.py", line 239, in _find_staves
    s.find_staves(self.lines_per_staff, scanlines, blackness, tolerance)
  File "/usr/local/lib/python3.7/site-packages/gamera/toolkits/musicstaves/stafffinder_miyao.py", line 621, in find_staves
    lp.rightangle, False)
  File "/usr/local/lib/python3.7/site-packages/gamera/args.py", line 33, in wrapper
    return f(*args, **kwargs)
TypeError: integer argument expected, got float
```

Image: 
[Einsiedeln__Stiftsbibliothek__Codex_611_186r.jpg.zip](https://github.com/DDMAL/Rodan/files/14010300/Einsiedeln__Stiftsbibliothek__Codex_611_186r.jpg.zip)
Text file:
[186r.txt](https://github.com/DDMAL/Rodan/files/14010302/186r.txt)

**Comment by JoyfulGen** [comment]
**Folio 158r** - MEI encoding job fails

Error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 773, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/MEI_encoding/MEI_encoding.py", line 98, in run_my_task
    mei_string = bm.process(jsomr, syls, classifier_table, width_mult, width_container, split_ranges)
  File "/code/Rodan/rodan/jobs/MEI_encoding/build_mei_file.py", line 855, in process
    pairs, classifier, width_container, staves, jsomr["page"], column_split_info
  File "/code/Rodan/rodan/jobs/MEI_encoding/build_mei_file.py", line 606, in build_mei
    bb = system_boxes[0]
IndexError: list index out of range
```

Image:
[Einsiedeln__Stiftsbibliothek__Codex_611_158v.jpg.zip](https://github.com/DDMAL/Rodan/files/14010329/Einsiedeln__Stiftsbibliothek__Codex_611_158v.jpg.zip)
Text file:
[158r.txt](https://github.com/DDMAL/Rodan/files/14010326/158r.txt)

**Comment by fujinaga** [comment]
> **Folio 186r** - Miyao staff finding job fails
> 
> Error message:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/code/Rodan/rodan/jobs/base.py", line 773, in run
>     retval = self.run_my_task(inputs, settings, arg_outputs)
>   File "/code/Rodan/rodan/jobs/heuristic_pitch_finding/base.py", line 77, in run_my_task
>     staves = sf.get_staves(image)
>   File "/code/Rodan/rodan/jobs/heuristic_pitch_finding/StaffFinding.py", line 33, in get_staves
>     self._find_staves(s)
>   File "/code/Rodan/rodan/jobs/heuristic_pitch_finding/StaffFinding.py", line 239, in _find_staves
>     s.find_staves(self.lines_per_staff, scanlines, blackness, tolerance)
>   File "/usr/local/lib/python3.7/site-packages/gamera/toolkits/musicstaves/stafffinder_miyao.py", line 621, in find_staves
>     lp.rightangle, False)
>   File "/usr/local/lib/python3.7/site-packages/gamera/args.py", line 33, in wrapper
>     return f(*args, **kwargs)
> TypeError: integer argument expected, got float
> ```
> 
> Image: [Einsiedeln__Stiftsbibliothek__Codex_611_186r.jpg.zip](https://github.com/DDMAL/Rodan/files/14010300/Einsiedeln__Stiftsbibliothek__Codex_611_186r.jpg.zip) Text file: [186r.txt](https://github.com/DDMAL/Rodan/files/14010302/186r.txt)

@JoyfulGen  can you post the Rodan Workflow for this? As well as the input image to the Stafffinder job?

**Comment by JoyfulGen** [comment]
> > **Folio 186r** - Miyao staff finding job fails
> 
> @JoyfulGen can you post the Rodan Workflow for this? As well as the input image to the Stafffinder job?

Here you go!
Output of the Dilate job (which is the input of Miyao): [Dilate output 186r.png.zip](https://github.com/DDMAL/Rodan/files/14024587/Dilate.output.186r.png.zip)
Workflow: [E2E full workflow Gen.json.zip](https://github.com/DDMAL/Rodan/files/14024590/E2E.full.workflow.Gen.json.zip)

**Comment by fujinaga** [comment]
@timothydereuse Can you look into these. The input looks good.
@JoyfulGen Can you post the screenshot of the Workflow?

**Comment by JoyfulGen** [comment]
Et hopla
<img width="734" alt="Workflow Gen" src="https://github.com/DDMAL/Rodan/assets/83373378/2abf8442-124e-4ce5-8ad8-2aca7fc4d2fd">

**Comment by fujinaga** [comment]
Beautiful. Thank you.

On Jan 25, 2024, at 05:47, Geneviève Gates-Panneton ***@***.***> wrote:

﻿

Et hopla
Workflow.Gen.png (view on web)<https://github.com/DDMAL/Rodan/assets/83373378/2abf8442-124e-4ce5-8ad8-2aca7fc4d2fd>

**Comment by homework36** [comment]
Fixed a messy while loop in StaffFinding (haven't cleaned up or made PR) so that the blackness parameter can be automatically adjusted until a threshold value. Also the error and exception will now come from StaffFinding when it fails instead of going into other downstream jobs. This works now for 158r and 269v but still fails on 186r with the same error message. 
Here are the remaining problems:
1. Rodan fails on 186r with the same error message as before but gamera works. Not sure what happens but will take more time to investigate.
```
Task Miyao Staff Finding[92552742-b82b-4b5d-b100-a609593705e5] raised unexpected: TypeError('integer argument expected, got float')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 773, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/heuristic_pitch_finding/base.py", line 83, in run_my_task
    staves = sf.get_staves(image)
  File "/code/Rodan/rodan/jobs/heuristic_pitch_finding/StaffFinding.py", line 40, in get_staves
    self._find_staves(s)
  File "/code/Rodan/rodan/jobs/heuristic_pitch_finding/StaffFinding.py", line 288, in _find_staves
    s.find_staves(self.lines_per_staff, scanlines, blackness, tolerance)
  File "/usr/local/lib/python3.7/site-packages/gamera/toolkits/musicstaves/stafffinder_miyao.py", line 621, in find_staves
    lp.rightangle, False)
  File "/usr/local/lib/python3.7/site-packages/gamera/args.py", line 33, in wrapper
    return f(*args, **kwargs)
TypeError: integer argument expected, got float
```
2. Rodan can only spot a corner of 269v. Attached is a screenshot of the output on NEON. 
![269v-output](https://github.com/DDMAL/Rodan/assets/70364944/46b1cdd2-db5e-460a-be54-571d719d1aed)
For this folio, the Rodan StaffFinding wrapper adjusts the blackness to 0.5. Upon testing on original gamera miyao, it is not be a problem with Rodan.
Here's the dilated output for 269v.
![Dilate - Onebit PNG dilated image 269](https://github.com/DDMAL/Rodan/assets/70364944/3302add0-e7a1-4f30-9def-1d9a84040767)
Here's the output from the original gamera miyao.
![gamera stafffinding for 269](https://github.com/DDMAL/Rodan/assets/70364944/839e7f80-b531-405f-8c02-b2eb91cd90dd)
With blackness > 0.5, miyao cannot spot any staff and return an empty list. If we keep lowering blackness, we will get sporadic pattern, still not the full page of staves, as such:
![Miyao Staff Finder - PNG image (Miyao results used as mask)](https://github.com/DDMAL/Rodan/assets/70364944/9949c8c5-eb90-4ac3-b723-8d00702d69c2)
My speculation is that the extra bottom line distracts miyao from telling staves from the background. Therefore, if we want to completely solve this problem we might need to work with the background removal part.

I will keep working on fixing the TypeError and update the progress. I will also test the modified version on folios that Rodan was able to run with this workflow.

**Comment by homework36** [comment]
Update: fixed the issue for wrapper. Now Rodan can finish the workflow and generate output for all three folios. Will clean up and make a PR for the current issue. But 269v still has problematic output from miyao (should we make a new issue?)

**Comment by fujinaga** [comment]
Yes, do make a new issue.

On Feb 16, 2024, at 13:19, Hanwen Zh ***@***.***> wrote:

﻿

Update: fixed the issue for wrapper. Now Rodan can finish the workflow and generate output for all three folios. Will clean up and make a PR for the current issue. But 269v still has problematic output from miyao (should we make a new issue?)
