### ISSUE TITLE
Iterating through the IC causes an unusual  TypeError

### ISSUE THREAD

**Issue by kyrieb-ekat** [DDMAL/Rodan#1179]
On Iteration 1 in the Interactive Classifier, using training data produced by a previous run, an odd error is produced: 

```
TypeError: ‘<’ not supported between instances of ‘bytes’ and ‘str’

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 773, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/interactive_classifier/wrapper.py", line 160, in run_my_task
    serialize_data(settings)
  File "/code/Rodan/rodan/jobs/interactive_classifier/interactive_classifier.py", line 316, in serialize_data
    settings['class_names_json'] = serialize_class_names_to_json(settings)
  File "/code/Rodan/rodan/jobs/interactive_classifier/interactive_classifier.py", line 302, in serialize_class_names_to_json
    return json.dumps(sorted(list(name_set)))
TypeError: '<' not supported between instances of 'bytes' and 'str'
```

This has happened on both staging and production, and was encountered by @JoyfulGen in her runs as well. 

This is preventing the further training of the IC, which hinders large scale processing through the NIC for the Bach Project.

**Comment by homework36** [comment]
Logs before this:
```[:45](https://ddmal.slack.com/archives/D05QM2K2TSN/p1718729140389509)
[2024-06-18 12:44:01,701: WARNING/ForkPoolWorker-18] The my_error_information method is not implemented properly (or not implemented at all). Exception:
[2024-06-18 12:44:01,702: WARNING/ForkPoolWorker-18] TypeError: 'NoneType' object is not subscriptable
[2024-06-18 12:44:01,702: WARNING/ForkPoolWorker-18] Using default sources for error information.
[2024-06-18 12:44:03,986: ERROR/ForkPoolWorker-18] Task Interactive Classifier[ddfe9d93-560a-4fd1-afdb-7fdefec33d03] raised unexpected: TypeError("'<' not supported between instances of 'bytes' and 'str'")
```

**Comment by homework36** [comment]
Fixed. Now waiting for staging to be updated.
