### ISSUE TITLE
The NIC has a bug

### ISSUE THREAD

**Issue by kyrieb-ekat** [DDMAL/Rodan#1238]
Discovered in #1235 wherein troubleshooting/bug hunting has revealed that, for some specific images, something about image edges presence (we think) cause the job to get stuck on processing and never progress to "finished" or "failed". Making a separate issue for addressing/unpacking the NIC specifically, with the debugging steps and examples describes in #1235 . 

It is possible to do a full e2e run with images which have previously failed by cropping the images so that only the page being OMR'd is visible, so this is nothing blocking or breaking, but is something to keep in mind for future e2e OMR runs.

**Comment by homework36** [comment]
Ater testing `rodan-main/code/rodan/jobs/gamera_rodan/wrappers/classification.py` at around line 103, I believe this is an issue inside Gamera 4 classify.py. The recursive method `_classify_list_automatic` is not going to terminate itself properly given some inputs (possibly with the edge)

**Comment by fujinaga** [comment]
That would make perfect sense. Will you be able to fix it? Ask co-pilot for assistance.

**Comment by homework36** [comment]
Should I fix it directly in gamera4 repo or the gamera wrapper in Rodan?

**Comment by fujinaga** [comment]
Whichever is easier for you, then create an issue to fix the other one.

**Comment by kyrieb-ekat** [comment]
Gamera4 will require fewer hoops to jump through than getting gamera (OG) going locally; if you do start with Gamera both Lucas and I got Gamera successfully working locally this past summer if you need any assistance/insight into what we did.

**Comment by homework36** [comment]
My understanding is that if we fix gamera 4 then it's better in general and we might not need to update the wrapper in Rodan. However, that's more complicated for sure and I need some time to play around with it, too. 
@kyrieb-ekat Yes I will definitely need your expertise! Thank you in advance!

**Comment by homework36** [comment]
While trying to get some xml files to test Gamera4, I was not able to reproduce the "processing" error in Rodan today.
Here's the workflow I used:

<img src="https://github.com/user-attachments/assets/051bba75-e185-49e7-92d4-b3b048703975" width="300" />


And my only inputs are 
(1) the layer from classifying that failed NIC

<img src="https://github.com/user-attachments/assets/05e6dca1-f972-4e17-a222-30c1ca0bf586" width="300" />

(2) the same gamera training xml (GitHub does not support .xml so I uploaded as .zip)

[Training Data GGP oct. 11 (2)(1).xml.zip](https://github.com/user-attachments/files/18606626/Training.Data.GGP.oct.11.2.1.xml.zip)

I got "failed" quickly and the error message from NIC says
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 791, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/gamera_rodan/wrappers/classification.py", line 91, in run_my_task
    cknn = gamera.knn.kNNNonInteractive(tempPath)
  File "/usr/local/lib/python3.7/site-packages/gamera/knn.py", line 686, in __init__
    classify.NonInteractiveClassifier.__init__(self, database, perform_splits)
  File "/usr/local/lib/python3.7/site-packages/gamera/classify.py", line 515, in __init__
    self.from_xml_filename(database)
  File "/usr/local/lib/python3.7/site-packages/gamera/classify.py", line 427, in from_xml_filename
    self._from_xml(stream)
  File "/usr/local/lib/python3.7/site-packages/gamera/classify.py", line 432, in _from_xml
    self.set_glyphs(database)
  File "/usr/local/lib/python3.7/site-packages/gamera/classify.py", line 558, in set_glyphs
    self.instantiate_from_images(self.database, self.normalize)
ValueError: Initial database of a non-interactive kNN classifier must have at least one element.
```

**Comment by homework36** [comment]
Found the files that get stuck in NIC now with help from @kyrieb-ekat 
They are very large images and result in very long cc list
