### ISSUE TITLE
Runtime Error for final page of workflow run

### ISSUE THREAD

**Issue by timwilfong** [DDMAL/Rodan#310]
I ran a workflow with "To Onebit," "Despeckle," and "Segment by Colour" (no interactive jobs) on 17 pages. The first 16 pages worked perfectly, but the final page failed on the Segment by Colour job and gave a runtime error. Also, I am (for some reason) unable to copy the error message anymore.

Here is the output of the despeckle job, as requested by @mrbannon 

![despeckle output](https://cloud.githubusercontent.com/assets/4247746/3246000/8088dc30-f177-11e3-9c05-28a7d202838e.png)

**Comment by lingxiaoyang** [comment]
The job `gamera.toolkits.lyric_extraction.plugins.lyric_extractor.segment_by_colour` still fails for the provided image. The test workflow:

`````
{
    "connections":[],
    "__version__":0.1,
    "workflow_jobs":[{
        "input_ports":[{"type":"input","id":1,"label":"input"}],
        "job_name":"gamera.toolkits.lyric_extraction.plugins.lyric_extractor.segment_by_colour",
        "output_ports":[{"type":"output","id":2,"label":"output"}],
        "job_settings":{"minimum_y_threshold": 10, "negative_bound": 10, "thickness_above": 0, "thickness_below": 0, "postive_bound": 10, "num_searches": 4}
    }],
    "name":"test #310",
    "description":""
}
`````

Removing it from RELEASE 1.0.0 as it depends on image content, not concerning the core system.

**Comment by lingxiaoyang** [comment]
Error: 
`````
Traceback (most recent call last):
  File "/srv/webapps/Rodan/rodan_env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/webapps/Rodan/rodan_env/local/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/webapps/Rodan/rodan/jobs/base.py", line 412, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/srv/webapps/Rodan/rodan/jobs/gamera/base.py", line 71, in run_my_task
    result_image = getattr(task_image, task_function)(**settings)
  File "/srv/webapps/Rodan/rodan_env/local/lib/python2.7/site-packages/gamera/toolkits/lyric_extraction/plugins/lyric_extractor.py", line 114, in __call__
    result = lyric_extractor_helper.extract_lyric_ccs(self, minimum_y_threshold, num_searches, negative_bound, postive_bound, thickness_above, thickness_below)
  File "/srv/webapps/Rodan/rodan_env/local/lib/python2.7/site-packages/gamera/toolkits/lyric_extraction/plugins/lyric_extractor_helper.py", line 236, in extract_lyric_ccs
    ccs = image.cc_analysis()
RuntimeError: Max label exceeded - change OneBitPixel type in pixel.hpp
`````

**Comment by mrbannon** [comment]
I'm closing this because:

- it's job package specific
- I did a quick test and couldn't recreate
