### ISSUE TITLE
Results Package - Diagnosis packaging mode is not fully implemented

### ISSUE THREAD

**Issue by deepio** [DDMAL/Rodan#499]
### Creating a results package object for diagnosis
```python
resultspackage_obj = {
            'workflow_run': 'http://localhost:8000/workflowrun/{0}/'.format(self.test_workflowrun.uuid),
            'output_ports': ['http://localhost:8000/outputport/{0}/'.format(self.output_a.output_port.uuid)],
            'packaging_mode': 2
        }
response = self.client.post("/resultspackages/", resultspackage_obj, format='json')
```
### Error
```python
Traceback (most recent call last):
  File "/code/Rodan/rodan/test/views/test_resultspackage.py", line 164, in test_one_port
    response = self.client.post("/resultspackages/", resultspackage_obj, format='json')
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/test.py", line 170, in post
    path, data=data, format=format, content_type=content_type, **extra)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/test.py", line 92, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/test.py", line 159, in request
    return super(APIClient, self).request(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/test.py", line 111, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/generics.py", line 246, in post
    return self.create(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py", line 21, in create
    self.perform_create(serializer)
  File "/code/Rodan/rodan/views/resultspackage.py", line 89, in perform_create
    registry.tasks["rodan.core.package_results"].apply_async((rp_id,))
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 551, in apply_async
    link=link, link_error=link_error, **options)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 743, in apply
    request=request, propagate=throw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 355, in eager_trace_task
    uuid, args, kwargs, request)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/core.py", line 356, in run
    raise NotImplementedError()  # [TODO]
NotImplementedError
```

### Possible Solutions
- implement it
- remove the packaging choice from resultspackages

**Comment by deepio** [comment]
```python
# rodan/models/resultspackage.py
PACKAGING_MODE_CHOICES = [
        (0, "Only endpoint resources"),
        (1, "All resources -- subdirectoried by resource names"),
        (2, "Diagnosis, including all inputs/outputs/settings -- subdirectoried by workflow job and resource names",),
    ]
```
