### ISSUE TITLE
Core job "create_resource" not registered in Rodan

### ISSUE THREAD

**Issue by JRegimbal** [DDMAL/Rodan#514]
Stack trace below:
```
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    | ERROR Internal Server Error: /resources/
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    | Traceback (most recent call last):
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     response = get_response(request)
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     response = self._get_response(request)
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     response = self.process_exception_by_middleware(e, request)
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     return view_func(*args, **kwargs)
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     return self.dispatch(request, *args, **kwargs)
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 489, in dispatch
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     response = self.handle_exception(exc)
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 449, in handle_exception
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     self.raise_uncaught_exception(exc)
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 486, in dispatch
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     response = handler(request, *args, **kwargs)
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/code/Rodan/rodan/views/resource.py", line 182, in post
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     registry.tasks['rodan.core.create_resource'].si(resource_id, mimetype).apply_async()
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 169, in <lambda>
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     __getitem__ = lambda x, i: x._get_current_object()[i]
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/registry.py", line 26, in __missing__
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    |     raise self.NotRegistered(key)
rodan_rodan.1.uf99mgpu9gxj@production-rodan-swarm    | NotRegistered: 'rodan.core.create_resource'
```

**Comment by deepio** [comment]
We want rodan jobs to be in the database (but still registered as celery tasks) and we want core rodan jobs to not be in the database but still be registered as celery tasks.

**Comment by deepio** [comment]
Both resources and resourcelists can be passed.

ecb08d987bb590e39d8805b71955f8161587b52b fixes the rest
