### ISSUE TITLE
Text Alignment job failed in staging

### ISSUE THREAD

**Issue by carrieeex** [DDMAL/Rodan#618]
I was trying to run the [full E2E OMR workflow](http://ddmal.music.mcgill.ca/e2e-omr-documentation/hints.html) in [staging](https://rodan-staging.simssa.ca/), with the updated text-alignment job for MS073, and it failed in the `Text Alignment` job with the following error:

> Error summary: TypeError: No matching signature found
> Error details:
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 412, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 704, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/code/Rodan/rodan/jobs/base.py", line 771, in run
>     retval = self.run_my_task(inputs, settings, arg_outputs)
>   File "/code/Rodan/rodan/jobs/text_alignment/text_alignment.py", line 75, in run_my_task
>     result = align.process(raw_image, transcript, model_name)
>   File "/code/Rodan/rodan/jobs/text_alignment/align_to_ocr.py", line 78, in process
>     image, eroded, angle = preproc.preprocess_images(raw_image)
>   File "/code/Rodan/rodan/jobs/text_alignment/image_preprocessing.py", line 176, in preprocess_images
>     img_bin = fill_corners(img_bin, fill_value=0, tol=None, fill_below_thresh=False)
>   File "/code/Rodan/rodan/jobs/text_alignment/image_preprocessing.py", line 139, in fill_corners
>     input_image = flood_fill(input_image, (0, 0), fill_value, tolerance=tol)
>   File "/usr/local/lib/python3.6/dist-packages/skimage/morphology/_flood_fill.py", line 104, in flood_fill
>     tolerance=tolerance)
>   File "/usr/local/lib/python3.6/dist-packages/skimage/morphology/_flood_fill.py", line 268, in flood
>     seed_value)
>   File "skimage/morphology/_flood_fill_cy.pyx", line 40, in skimage.morphology._flood_fill_cy.__pyx_fused_cpdef
> TypeError: No matching signature found
> ```
> 

To replicate this issue:

Rather than testing it with the full OMR workflow, one can use a reduced workflow with text-alignment in staging:
![image](https://user-images.githubusercontent.com/59303880/128928104-d384107c-5a86-4dd2-8324-3090bd232e67.png)

where the setting for the `Resize Image` is 0.31 according to the [documentation](https://github.com/DDMAL/e2e-omr-resources/tree/main/document_analysis/MS_73#training-data), and choose "ms073-2021" model in the drop-down menu of the `Text Alignment` job.

The input of the `Fast Pixelwise Analysis of Music Document` for staging is [here](https://github.com/DDMAL/e2e-omr-resources/tree/main/document_analysis/MS_73/models/staging), and the .txt input for the `Text Alignment` job can be found [here](https://github.com/DDMAL/e2e-omr-resources/tree/main/text_alignment/MS073/extracted_text).

**Comment by carrieeex** [comment]
also tried with Salzinnes OCR model in staging, had the same error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 771, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/text_alignment/text_alignment.py", line 75, in run_my_task
    result = align.process(raw_image, transcript, model_name)
  File "/code/Rodan/rodan/jobs/text_alignment/align_to_ocr.py", line 78, in process
    image, eroded, angle = preproc.preprocess_images(raw_image)
  File "/code/Rodan/rodan/jobs/text_alignment/image_preprocessing.py", line 176, in preprocess_images
    img_bin = fill_corners(img_bin, fill_value=0, tol=None, fill_below_thresh=False)
  File "/code/Rodan/rodan/jobs/text_alignment/image_preprocessing.py", line 139, in fill_corners
    input_image = flood_fill(input_image, (0, 0), fill_value, tolerance=tol)
  File "/usr/local/lib/python3.6/dist-packages/skimage/morphology/_flood_fill.py", line 104, in flood_fill
    tolerance=tolerance)
  File "/usr/local/lib/python3.6/dist-packages/skimage/morphology/_flood_fill.py", line 268, in flood
    seed_value)
  File "skimage/morphology/_flood_fill_cy.pyx", line 40, in skimage.morphology._flood_fill_cy.__pyx_fused_cpdef
TypeError: No matching signature found
```

**Comment by timothydereuse** [comment]
Well, I know what caused the problem: while i was updating text-alignment to include scripts for creating training data, I tweaked a few tiny things in the image preprocessing - most importantly, this line: https://github.com/DDMAL/Rodan/blob/e32dd394b2954ba512fd5ccb4767aa5ccaf14488/rodan/jobs/text_alignment/image_preprocessing.py#L162

We used to convert using skimage's `rgb2grayscale` method, but this is deprecated behavior if the image is actually rgba. I fixed this, making sure the image does not have an alpha channel before converting, and in the process added an explicit conversion to `float32` to keep things clean. Scikit-image appears to not like this; however, I can't reproduce this bug in any environment outside of Rodan, even when using the exact same version of python and scikit-image. There are related bugs out there on stackoverflow, though.

**Comment by timothydereuse** [comment]
Even stranger is the fact that this bug only happens after one successful run of the `fill_corners` method. Since we are passing the same image type to each method, it must be some incompatibility between the `float32` image and the specific parameters for that second flood fill.

**Comment by timothydereuse** [comment]
It appears the fix worked!
