### ISSUE TITLE
Text Alignment fails when run after Calvo Classifier, until gpu-celery container is restarted

### ISSUE THREAD

**Issue by timothydereuse** [DDMAL/Rodan#671]
Running text alignment in rodan on staging or production occasionally results in this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/base.py", line 771, in run
    retval = self.run_my_task(inputs, settings, arg_outputs)
  File "/code/Rodan/rodan/jobs/text_alignment/text_alignment.py", line 76, in run_my_task
    result = align.process(raw_image, transcript, model_name)
  File "/code/Rodan/rodan/jobs/text_alignment/align_to_ocr.py", line 83, in process
    all_chars = perform_ocr.recognize_text_strips(image, cc_strips, ocr_model_name, verbose)
  File "/code/Rodan/rodan/jobs/text_alignment/perform_ocr.py", line 69, in recognize_text_strips
    tf.config.set_visible_devices([], 'GPU')
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/config.py", line 523, in set_visible_devices
    context.context().set_visible_devices(devices, device_type)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/context.py", line 1438, in set_visible_devices
    "Visible devices cannot be modified after being initialized")
RuntimeError: Visible devices cannot be modified after being initialized
```

This does not happen when running Rodan locally. Curiously, it also does not happen if you get a shell into the live `gpu-celery` container (with `docker exec -it [container id] bash`), navigate to the `text_alignment` directory, and run `python perform_ocr.py` or any other task that requires the Calamari OCR library; these all seem to work perfectly fine.

What I have managed to track down is that this only happens when running an OCR task through Celery, and it never happens on a "freshly started" container; i.e. if you kill the gpu-celery container, or scale it to 0 and back to 1 with `docker service scale gpu-celery=0` and `docker service scale gpu-celery=1`, then when it's back up, if you run text alignment in isolation it will work fine. As far as I can tell it only crashes when you run the Calvo classifier before it.

It looks like this method is the culprit (called in the `tfaip` library, which is used by the Calamari OCR library): https://www.tensorflow.org/api_docs/python/tf/config/set_visible_devices. The "Runtime is already initialized" by the Calvo Classifier, so it throws an error. We need to figure out a way around this, so that the runtime is not re-initialized if it doesn't have to be. Unfortunately, this code is buried deep in the `tfaip` library,  and I'd rather not touch that huge thing...

We can make changes to Calamari OCR itself or open issues there, as Christoph (the project's maintainer) is quite responsive to problems. Note that we currently install Calamari OCR from a forked repository associated with my own github account just so that I can pin the requirements file to use only specific versions of things, which the main Calamari Repo does not do (nothing else is changed).

**Comment by timothydereuse** [comment]
Fixed in https://github.com/DDMAL/Rodan/pull/721.
