### ISSUE TITLE
Cannot build neon_wrapper locally

### ISSUE THREAD

**Issue by softcat477** [DDMAL/Rodan#840]
### Steps to recreate
1. `git clone --recurse-submodules https://github.com/DDMAL/neon-wrapper`
2. `cd neon_wrapper `
3. `git submodule update --init`
4. `git submodule update --remote`
5. `yarn install`
6. `yarn build (failed)`

```
yarn run v1.22.19
$ ./setup-verovio-rodan && yarn upgrade verovio-dev && ./correct-import && webpack --config webpack.config.js && cp -R Neon/assets Neon/src/workers static/Neon && cp editor.html static/editor.html
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Rebuilding all packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ verovio-dev@2.2.0-4
info All dependencies
└─ verovio-dev@2.2.0-4
⬡ webpack: Starting Build
ℹ ｢atl｣: Using typescript@3.9.7 from typescript
ℹ ｢atl｣: Using tsconfig.json from /Users/softcat/Softcat/Sandbox/Rodan/rodan-main/code/rodan/jobs/neon_wrapper/tsconfig.json
Error in bail mode: Error: callback(): The callback was already called.
    at context.callback (/Users/softcat/Softcat/Sandbox/Rodan/rodan-main/code/rodan/jobs/neon_wrapper/node_modules/loader-runner/lib/LoaderRunner.js:106:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) Error: callback(): The callback was already called.
    at context.callback (/Users/softcat/Softcat/Sandbox/Rodan/rodan-main/code/rodan/jobs/neon_wrapper/node_modules/loader-runner/lib/LoaderRunner.js:106:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by homework36** [comment]
Got similar(same?) issue now with same steps
```
yarn install v1.22.22
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[1/3] ⠈ leveldown
[-/3] ⠈ waiting...
error /Users/homework36/Documents/Projects/Rodan/rodan-main/code/rodan/jobs/neon_wrapper/node_modules/leveldown: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments: 
Directory: /Users/homework36/Documents/Projects/Rodan/rodan-main/code/rodan/jobs/neon_wrapper/node_modules/leveldown
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@22.8.0 | darwin | arm64
gyp info find Python using Python version 3.11.5 found at "/Users/homework36/anaconda3/bin/python3"

gyp info spawn /Users/homework36/anaconda3/bin/python3
gyp info spawn args [
gyp info spawn args '/opt/homebrew/Cellar/node/22.8.0/libexec/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/homework36/Documents/Projects/Rodan/rodan-main/code/rodan/jobs/neon_wrapper/node_modules/leveldown/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/opt/homebrew/Cellar/node/22.8.0/libexec/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/homework36/Library/Caches/node-gyp/22.8.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/Users/homework36/Library/Caches/node-gyp/22.8.0',
gyp info spawn args '-Dnode_gyp_dir=/opt/homebrew/Cellar/node/22.8.0/libexec/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/Users/homework36/Library/Caches/node-gyp/22.8.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/Users/homework36/Documents/Projects/Rodan/rodan-main/code/rodan/jobs/neon_wrapper/node_modules/leveldown',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/db/builder.o
In file included from ../deps/leveldb/leveldb-1.20/db/builder.cc:7:
In file included from ../deps/leveldb/leveldb-1.20/db/filename.h:14:
In file included from ../deps/leveldb/leveldb-1.20/port/port.h:16:
In file included from ../deps/leveldb/leveldb-1.20/port/port_posix.h:47:
../deps/leveldb/leveldb-1.20/port/atomic_pointer.h:59:3: warning: 'OSMemoryBarrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_thread_fence() from <atomic> instead [-Wdeprecated-declarations]
  OSMemoryBarrier();
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libkern/OSAtomicDeprecated.h:751:9: note: 'OSMemoryBarrier' has been explicitly marked deprecated here
void    OSMemoryBarrier( void );
        ^
1 warning generated.

......
error: libtool: file: Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env.o is not an object file (not allowed in a library)
error: libtool: file: Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/filter_policy.o is not an object file (not allowed in a library)
error: libtool: file: Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/hash.o is not an object file (not allowed in a library)
error: libtool: file: Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/logging.o is not an object file (not allowed in a library)
error: libtool: file: Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/options.o is not an object file (not allowed in a library)
error: libtool: file: Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/status.o is not an object file (not allowed in a library)
error: libtool: file: Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/port/port_posix.o is not an object file (not allowed in a library)
error: libtool: file: Release/obj.target/leveldb/deps/leveldb/leveldb-1.20/util/env_posix.o is not an object file (not allowed in a library)
make[1]: *** [Release/leveldb.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/opt/homebrew/Cellar/node/22.8.0/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Darwin 23.6.0
gyp ERR! command "/opt/homebrew/Cellar/node/22.8.0/bin/node" "/opt/homebrew/Cellar/node/22.8.0/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/homework36/Documents/Projects/Rodan/rodan-main/code/rodan/jobs/neon_wrapper/node_modules/leveldown
gyp ERR! node -v v22.8.0
gyp ERR! node-gyp -v v10.1.0


make: *** [rodan-main/code/rodan/jobs/neon_wrapper/static/editor.html] Error 1
```

**Comment by homework36** [comment]
I used the following:
node: v12.22.12
yarn: 1.22.22
npm: 8.10.0

Cannot pass yarn build and `make run` cannot work.

**Comment by homework36** [comment]
Worked. 
Installed the packages mentioned above with the exact version.
(Also, remember to clear the cache for them if there's a failed installation.)
Then do `make remote_jobs` before `make run`.
We should update instructions somewhere to include this piece of information.
