### ISSUE TITLE
Django Upgrade to 2.0

### ISSUE THREAD

**Issue by sabrina0822** [DDMAL/Rodan#900]
We currently use django version 1.11, the goal is to upgrade to version 3.2 (since our postgres version only supports this django version). However, I am first going to experiment with updating to version 2.0 and see how long that takes. 

As of right now, I have been unable to build the nginx container because it keeps on throwing django errors which I am slowly going through. @kqct do you know why the nginx dockerfile runs docker commands? 
So far these fixes have mainly been updating other django related requirements in our requirements.txt file

**Comment by sabrina0822** [comment]
Originally I had thought that I would be able to speed up development by only building the nginx container. But, since the nginx dockerfile builds off of rodan-client and rodan-main (which build off of py3-celery) I have to wait 40 minutes for my changes to take place.

**Comment by sabrina0822** [comment]
Got local host to run locally and can run jobs but there are a few other traceback issues that are coming from misc. locations. 

'''
Traceback (most recent call last):
  File "/code/Rodan/rodan/test/views/test_userpreference.py", line 21, in test_post
    response = self.client.post("/api/userpreferences/", up_obj, format="json")
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 290, in post
    path, data=data, format=format, content_type=content_type, **extra)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 212, in post
Creating test database for alias 'default'...
    return self.generic('POST', path, data, content_type, **extra)
  File "/usr/local/lib/python3.7/site-packages/django/test/client.py", line 416, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 279, in request
    return super(APIClient, self).request(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 231, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/test/client.py", line 501, in request
    six.reraise(*exc_info)
  File "/usr/local/lib/python3.7/site-packages/django/utils/six.py", line [68](https://github.com/DDMAL/Rodan/actions/runs/5061780107/jobs/9086454617?pr=908#step:7:69)6, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 4[86](https://github.com/DDMAL/Rodan/actions/runs/5061780107/jobs/9086454617?pr=908#step:7:87), in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/Rodan/rodan/views/userpreference.py", line 40, in post
    match = resolve(path)
NameError: name 'resolve' is not defined
'''

**Comment by sabrina0822** [comment]
This is completed! Wanyi just needs to create new test images with the upgraded requirements so that our PR can pass the CI tests. Then it can be merged into develop

**Comment by fujinaga** [comment]
Good job!

**Comment by sabrina0822** [comment]
Merged into develop!
