### ISSUE TITLE
Django Upgrade to 2.2.28

### ISSUE THREAD

**Issue by sabrina0822** [DDMAL/Rodan#918]
Following the upgrade of django 2.0 I attempted to upgrade to django 2.1 and faced an issue with the database. I did some research online and they recommended just upgrading directly to 2.2 but this unfortunately did not fix the issue. It seems as though there are duplicate entries in the database for an unknown reason (possibly due to modifications in the permissions that were necessary).

This is the most recent traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "auth_permission_content_type_id_codename_01ab375a_uniq"
DETAIL:  Key (content_type_id, codename)=(4, view_user) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 257, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/usr/local/lib/python3.7/site-packages/django/core/management/sql.py", line 51, in emit_post_migrate_signal
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/code/Rodan/rodan/models/__init__.py", line 61, in add_view_user_permission
    Permission.objects.get_or_create(codename='view_user', name='View User', content_type=content_type)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 541, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 583, in _create_object_from_params
    raise e
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 575, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 744, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 782, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 911, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "auth_permission_content_type_id_codename_01ab375a_uniq"
DETAIL:  Key (content_type_id, codename)=(4, view_user) already exists.
```

**Comment by malajvan** [comment]
We have made multiple changes in the branch `django_2.2`. We could start the containers and create projects, upload resources but jobs seems to be failing. Below is the Errors from ci-jobs test cases.
```
ERROR: test_post_image (Rodan.rodan.test.views.test_resource.ResourceProcessingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/Rodan/rodan/test/views/test_resource.py", line 224, in test_post_image
    "/api/resources/", resource_obj, format="multipart", resource_type=rt
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 294, in post
    path, data=data, format=format, content_type=content_type, **extra)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 207, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 232, in generic
    method, path, data, content_type, secure, **extra)
  File "/usr/local/lib/python3.7/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 283, in request
    return super().request(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 235, in request
    request = super().request(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/Rodan/rodan/views/resource.py", line 217, in post
    registry.tasks['rodan.core.create_resource'].si(resource_id, mimetype).apply_async()
  File "/usr/local/lib/python3.7/site-packages/celery/canvas.py", line 235, in apply_async
    return _apply(args, kwargs, **options)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 564, in apply_async
    link=link, link_error=link_error, **options)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 776, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 429, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/core.py", line 70, in run
    shutil.copy(infile_path, tmpfile)
  File "/usr/local/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/tmpln2b8npo/projects/17c3a5d7e3bb46ec8f5ce28802e86db9/resources/acdacf93a24f44fa9355aab84add6c34/original_file'

======================================================================
ERROR: test_post_image_claiming_txt (Rodan.rodan.test.views.test_resource.ResourceProcessingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/Rodan/rodan/test/views/test_resource.py", line 244, in test_post_image_claiming_txt
    response = self.client.post("/api/resources/", resource_obj, format="multipart")
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 294, in post
    path, data=data, format=format, content_type=content_type, **extra)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 207, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 232, in generic
    method, path, data, content_type, secure, **extra)
  File "/usr/local/lib/python3.7/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 283, in request
    return super().request(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 235, in request
    request = super().request(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/Rodan/rodan/views/resource.py", line 217, in post
    registry.tasks['rodan.core.create_resource'].si(resource_id, mimetype).apply_async()
  File "/usr/local/lib/python3.7/site-packages/celery/canvas.py", line 235, in apply_async
    return _apply(args, kwargs, **options)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 564, in apply_async
    link=link, link_error=link_error, **options)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 776, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 429, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/core.py", line 70, in run
    shutil.copy(infile_path, tmpfile)
  File "/usr/local/lib/python3.7/shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/tmpln2b8npo/projects/3930f5ad0f7a4bc0b7e29755146aaa62/resources/e0c5c3c93a1f42e6a6b83c4ed62e51be/original_file'

======================================================================
ERROR: test_post (Rodan.rodan.test.views.test_resource.ResourceViewTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/Rodan/rodan/test/views/test_resource.py", line 67, in test_post
    response = self.client.post("/api/resources/", resource_obj, format="multipart")
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 294, in post
    path, data=data, format=format, content_type=content_type, **extra)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 207, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 232, in generic
    method, path, data, content_type, secure, **extra)
  File "/usr/local/lib/python3.7/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 283, in request
    return super().request(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/test.py", line 235, in request
    request = super().request(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/Rodan/rodan/views/resource.py", line 217, in post
    registry.tasks['rodan.core.create_resource'].si(resource_id, mimetype).apply_async()
  File "/usr/local/lib/python3.7/site-packages/celery/canvas.py", line 235, in apply_async
    return _apply(args, kwargs, **options)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 564, in apply_async
    link=link, link_error=link_error, **options)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 776, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 429, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/code/Rodan/rodan/jobs/core.py", line 61, in run
    mimetype = fileparse(infile_path)
  File "/code/Rodan/rodan/jobs/resource_identification.py", line 139, in fileparse
    magic_mime = magic.from_file(filename, mime=True)
  File "/usr/local/lib/python3.7/site-packages/magic/__init__.py", line 180, in from_file
    return m.from_file(filename)
  File "/usr/local/lib/python3.7/site-packages/magic/__init__.py", line 113, in from_file
    with _real_open(filename):
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/tmpln2b8npo/projects/dfd88a068fe44a268961f112b96a72b5/resources/1e360e7feabc4da09e8989a78125b32b/original_file'

======================================================================
FAIL: test_post_bad_image (Rodan.rodan.test.views.test_resource.ResourceProcessingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/Rodan/rodan/test/views/test_resource.py", line 274, in test_post_bad_image
    self.assertEqual(self.test_resource1.resource_type.mimetype, "text/plain")
AssertionError: 'application/octet-stream' != 'text/plain'
- application/octet-stream
+ text/plain


----------------------------------------------------------------------
Ran 154 tests in 714.668s

FAILED (failures=1, errors=3)
Destroying test database for alias 'default'...
```

**Comment by sabrina0822** [comment]
Update to this issue: 

Unfortunately although all functionality looks good when testing the website locally we are still unable to pass the CI tests (same error as what Van added). Moderatly frustrating because we can't recreate the issue locally. 

Talked to Van and we are going to undo the work we've done from the past two days and try to solve the error a different way. Seems like the way Django deals with absolute vs. relative paths changed from version 2.0 to 2.1 and therefore things aren't working.
