### ISSUE TITLE
Latency issues when importing workflow from file in Chrome

### ISSUE THREAD

**Issue by PythonSemicolon** [DDMAL/Rodan#949]
When using the "Import workflow from file" option in the workflows of a project (**on Chrome specifically**), Rodan will seemingly load forever. This happens about half of the time, and usually occurs the first time performing the action. If you abandon the operation (i.e., refresh page or close loading message), the workflow will not open correctly and lose anywhere between a few and all of its connections. Occurs for both regular and super users on staging. Errors thrown in console vary between 403s, 404s and 409s between instances of this bug.

I cannot seem to reproduce this issue anymore, and have asked others to attempt to on different machines and browsers and they also cannot. However, it was definitely happening consistently when we first noticed it, and we waited a solid 5 minutes for the workflow to load before abandoning (leading me to believe it is not just due to slow performance).

@sabrina0822

**Comment by sabrina0822** [comment]
Found a fun little error message on the production rodan-main docker container relating to this 

```
 ERROR Internal Server Error: /api/workflows/
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
     self.connect()
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 189, in connect
     self.connection = self.get_new_connection(conn_params)
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
     connection = Database.connect(**conn_params)
   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
 psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known
 
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
     response = get_response(request)
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
     response = self._get_response(request)
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
     return view_func(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
     return self.dispatch(request, *args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 489, in dispatch
     response = self.handle_exception(exc)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 449, in handle_exception
     self.raise_uncaught_exception(exc)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 477, in dispatch
     self.initial(request, *args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 394, in initial
     self.perform_authentication(request)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 320, in perform_authentication
     request.user
   File "/usr/local/lib/python3.7/site-packages/rest_framework/request.py", line 381, in __getattribute__
     return super(Request, self).__getattribute__(attr)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/request.py", line 196, in user
     self._authenticate()
   File "/usr/local/lib/python3.7/site-packages/rest_framework/request.py", line 345, in _authenticate
     user_auth_tuple = authenticator.authenticate(self)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/authentication.py", line 188, in authenticate
     return self.authenticate_credentials(token)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/authentication.py", line 193, in authenticate_credentials
     token = model.objects.select_related('user').get(key=key)
   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 374, in get
     num = len(clone)
   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 232, in __len__
     self._fetch_all()
   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
     self._result_cache = list(self._iterable_class(self))
   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 887, in execute_sql
     cursor = self.connection.cursor()
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
     return self._cursor()
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
     self.ensure_connection()
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
     self.connect()
   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 94, in __exit__
     six.reraise(dj_exc_type, dj_exc_value, traceback)
   File "/usr/local/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
     raise value.with_traceback(tb)
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
     self.connect()
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 189, in connect
     self.connection = self.get_new_connection(conn_params)
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
     connection = Database.connect(**conn_params)
   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
 django.db.utils.OperationalError: could not translate host name "postgres" to address: Name or service not known
 
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.project.Project'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.userpreference.UserPreference'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.workflowrun.WorkflowRun'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.resource.Resource'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /code/Rodan/rodan/jobs/load.py:298: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
   resource_types = yaml.load(f)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.project.Project'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.workflow.Workflow'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.workflowrun.WorkflowRun'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.workflowjobgroup.WorkflowJobGroup'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.resource.Resource'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /code/Rodan/rodan/jobs/load.py:298: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
   resource_types = yaml.load(f)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.workflow.Workflow'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.project.Project'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.workflowrun.WorkflowRun'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.workflowjobgroup.WorkflowJobGroup'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 /usr/local/lib/python3.7/site-packages/rest_framework/pagination.py:208: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'rodan.models.userpreference.UserPreference'> QuerySet.
   paginator = self.django_paginator_class(queryset, page_size)
 ERROR Internal Server Error: /api/userpreferences/
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
     return self.cursor.execute(sql, params)
 psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "rodan_userpreference_user_id_key"
 DETAIL:  Key (user_id)=(45) already exists.
 
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
     response = get_response(request)
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
     response = self._get_response(request)
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
     return view_func(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
     return self.dispatch(request, *args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 489, in dispatch
     response = self.handle_exception(exc)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 449, in handle_exception
     self.raise_uncaught_exception(exc)
   File "/usr/local/lib/python
 
 ERROR Internal Server Error: /api/userpreferences/
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
     return self.cursor.execute(sql, params)
 psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "rodan_userpreference_user_id_key"
 DETAIL:  Key (user_id)=(45) already exists.
 
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
     response = get_response(request)
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
     response = self._get_response(request)
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
     return view_func(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
     return self.dispatch(request, *args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 489, in dispatch
     response = self.handle_exception(exc)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 449, in handle_exception
     self.raise_uncaught_exception(exc)
   File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 486, in dispatch
     response = handler(request, *args, **kwargs)
   File "/code/Rodan/rodan/views/userpreference.py", line 56, in post
     userpreference_obj.save()
   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 808, in save
     force_update=force_update, update_fields=update_fields)
   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 838, in save_base
     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 924, in _save_table
     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
   File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 963, in _do_insert
     using=using, raw=raw)
   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
     return getattr(self.get_queryset(), name)(*args, **kwargs)
   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1079, in _insert
     return query.get_compiler(using=using).execute_sql(return_id)
   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
     cursor.execute(sql, params)
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
     return self.cursor.execute(sql, params)
   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 94, in __exit__
     six.reraise(dj_exc_type, dj_exc_value, traceback)
   File "/usr/local/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
     raise value.with_traceback(tb)
   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
     return self.cursor.execute(sql, params)
 django.db.utils.IntegrityError: duplicate key value violates unique constraint "rodan_userpreference_user_id_key"

```

**Comment by PythonSemicolon** [comment]
This issue seems to be occurring the majority of time (>75%) on production and frequently (~50%) on staging.

Notes on the client-side errors thrown in this issue:
- errors range between 401s, 403s, 404s and 409s.
- every time the workflow fails to load, a 404 occurs. This is the only error that is consistently thrown by the operation failing.
- a 403 occurs on the initial load of the page, seemingly unrelated to this issue.
- more 403s and 401s occur on occasion on staging.
- a 409 always occurs when opening a workflow that didn't finish loading (one with missing connections)
